<?php

namespace AppBundle\Repository;

/**
 * BcsBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
