<?php

namespace AppBundle\Repository;

/**
 * BcsItemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsItemTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
