<?php

namespace AppBundle\Repository;

/**
 * BcsItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsItemRepository extends \Doctrine\ORM\EntityRepository
{
}
