<?php

namespace AppBundle\Repository;

/**
 * BcsItemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsItemCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
