<?php

namespace AppBundle\Repository;

/**
 * BcsLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
