<?php

namespace AppBundle\Repository;

/**
 * BcsMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
