<?php

namespace AppBundle\Repository;

/**
 * BcsMovementDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsMovementDetailRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyAll(){
        return $this->createQueryBuilder('a')
            ->where('a.mvdQuantity > 1')
            ->getQuery()->getResult();
    }
}
