<?php

namespace AppBundle\Repository;

/**
 * BcsOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueryOrderInProgress(){
        return $this->createQueryBuilder('a')
            ->where('a.ordStatus = 1');
    }
}
