<?php

namespace AppBundle\Repository;

/**
 * BcsObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
