<?php

namespace AppBundle\Repository;

/**
 * BcsOrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsOrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
