<?php

namespace AppBundle\Repository;

/**
 * BcsSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
