<?php

namespace AppBundle\Repository;

/**
 * BcsSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsSupplierRepository extends \Doctrine\ORM\EntityRepository
{
}
