<?php

namespace AppBundle\Repository;

/**
 * BcsTypeMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsTypeMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
