<?php

namespace AppBundle\Repository;

/**
 * BcsUnitOfMeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsUnitOfMeasureRepository extends \Doctrine\ORM\EntityRepository
{
}
