<?php

namespace AppBundle\Repository;

/**
 * BcsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcsUserRepository extends \Doctrine\ORM\EntityRepository
{
}
